<!--
This template is for use for the SOFT165 practical exercises.  
It has been generated by Dr Shirley Atkinson for the purposes of teaching.
-->
<?php
require_once 'public/header.php';

?>
<body class="bg-info">
    <div class="container-fluid col-md-6 offset-md-3">
    <div class="row">
        <div class="card mt-3">
            Welcome to our treasure hunt page.  
            Follow the links below to try out your luck.
            <br><br><br><br><br>
            Adjust this main page to provide links to your pages.
            <br><br><br><br><br>
        </div>
    </div>
    </div>
     
 <?php include_once 'public/footer.php'; ?>
